# Generated by Django 3.0.7 on 2020-06-22 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('scale', models.IntegerField()),
                ('location', models.CharField(max_length=60)),
                ('homepage', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carear', models.CharField(max_length=50)),
                ('carear_start', models.IntegerField()),
                ('carear_end', models.IntegerField()),
                ('recruit_page', models.CharField(max_length=50)),
                ('uploed', models.TimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mains.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=100)),
                ('detail', models.TextField()),
                ('web_page', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RequireStack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('recruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mains.Recruit')),
            ],
        ),
    ]
