# Generated by Django 2.1.15 on 2020-06-24 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('scale', models.IntegerField()),
                ('location', models.CharField(max_length=60)),
                ('homepage', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carear', models.CharField(max_length=50)),
                ('carear_start', models.IntegerField()),
                ('carear_end', models.IntegerField()),
                ('recruit_page', models.CharField(max_length=50)),
                ('uploed', models.TimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mains.Company')),
            ],
        ),
        migrations.CreateModel(
            name='RequireStack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_now', models.BooleanField(default=True)),
                ('recruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mains.Recruit')),
            ],
        ),
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('img', models.CharField(max_length=100, null=True)),
                ('detail', models.TextField(null=True)),
                ('web_page', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
