# Generated by Django 2.1.15 on 2020-06-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skillstack',
            old_name='web_page',
            new_name='webpage',
        ),
        migrations.RemoveField(
            model_name='skillstack',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='skillstack',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='skillstack',
            name='stackshareLink',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
